# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [Elimuhub7407, user2]
patreon: # Replace with a single Patreon Elimuhub7407 
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi Elimuhub7407
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay Elimuhub7407
issuehunt: # Replace with a single IssueHunt Elimuhub7407
otechie: # Replace with a single Otechie Elimuhub7407
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://github.com/python-poetry/poetry-export-plugin/network/Elimuhub7407', 'link2']
